apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: istio-base
  namespace: istio-system
spec:
  interval: 15m
  chart:
    spec:
      chart: base
      version: "1.27.1"
      sourceRef:
        kind: HelmRepository
        name: istio
        namespace: flux-system
  values:
  global:
    hub: gcr.io/istio-release   # or docker.io/istio
    tag: "1.27.1"