apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: istio-ingressgateway
  namespace: istio-system
spec:
  interval: 15m
  chart:
    spec:
      chart: gateway
      version: "1.27.1"
      sourceRef:
        kind: HelmRepository
        name: istio
        namespace: flux-system
  values:
    global:
      hub: gcr.io/istio-release
      tag: "1.27.1"
    service:
      type: LoadBalancer
